### ISSUE TITLE
Corrupt flash upload

### ISSUE THREAD

**Issue by TyberiusPrime** [TheKikGen/stm32-tkg-hid-bootloader#1]
First off, thanks for writing this bootloader, it is very clearly structured and hackable and who doesn't like it's tiny size, both in binary and in code!

Unfortunatly, on my blue pills, it fails to flash correctly and my binaries don't run.

I've created 'combined' binaries (bootloader-padded-to-4096 bytes)/blinky,
and in those the board does blink correctly.

Now I enter the bootloader, flash the same blinky binary I used to create the combined binary,
and it does no longer blink.

I've retrieved the flash and I found, that the bootloader-flashed-blinky
- the first 4096 bytes are identical (as they should)
- the bootloader-flashed binary is offset by one byte 'to the right'. There is a 0x90 byte *before* the binary 
- correcting for this, there starts to be occasional differences at byte 4160
- after byte 4440 basically every byte is different.

(all of this is with bootloader_only/binaries/tkg_hid_generic_pc13.bin as well as with a version I stripped down to 'enter on double reset, don't touch peripherals at all' - I initially thought the issue was one of the MCU being in a state where my rust binary wouldn't initialize it correctly).

Now the corruption could be a timing issue - I'm flashing from linux. I don't see a CRC in the flash code, correct?

But the of by one - if I shift my combined binary by that 0x90, it stops working as well....

Sorry for the wall of text.
Hopefully you have some insights for me :).

**Comment by TheKikGen** [comment]
Hi ,

Yes. probably a timing issue. Try to play with timing in the cli source.
I tested on Linux but not so deeply, because for various reasons, my main development platform is under WIN10. 
Can you test on WIN ?

No CRC but I'm seriously thinking about adding it !  

One important thing : your apps must be linked to start at the right address, else the jump from the bootloader will not work.
```
MEMORY
{
  ram (rwx) : ORIGIN = 0x20000000, LENGTH = 20K
  rom (rx)  : ORIGIN = 0x08001000, LENGTH = 124K
}
```
Check "Adding a new upload method to the Arduino platform" in the readme.

**Comment by TheKikGen** [comment]
I made an update of TKG-FLASH including an increased delay between packet from 500 uS to 1 mS.
